train_file: ['/kaggle/input/processed-rad-vqa-dataset/trainset.json']

test_file: ['/kaggle/input/processed-rad-vqa-dataset/testset.json']
answer_list: '/kaggle/input/processed-rad-vqa-dataset/answer_list.json'

vqa_root: /kaggle/input/processed-rad-vqa-dataset/images/'

image_res: 384
batch_size_train: 8
batch_size_test: 8
k_test: 128

alpha: 0.4
distill: True
warm_up: True

eos: '[SEP]'

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 1, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}







